EMBED_NAME_FOOTER: NOMBRE DEL FOOTER DE LOS EMBEDS
EMBED_LINK_FOOTER: https://images-ext-1.discordapp.net/external/3ezr-05YQxBbtP5hmdsonX-CrU4PTf2vrKrlrehjEzw/https/yt3.ggpht.com/a/AGF-l7-M9uNRUVm2B9cr7QoDSF8YF5Lfmf_gfAwtKA%3Ds400-c-k-c0xffffffff-no-rj-mo
AUTOMESSAGE_TITLE: Título del mensaje automático
AUTOMESSAGE_MESSAGE: Descripción del mensaje automático
AUTOMESSAGE_CHANNEL_ID: LA ID DEL CANAL PARA EL MENSAJE AUTOMÁTICO